name: Deploy
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
      - name: Build project
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: production-files
          
